import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { SalaryProvider } from "./products/context/page";
import { Geist, Geist_Mono } from "next/font/google";
import Layout from "./layouts/page";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Store managment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class">
          <SalaryProvider>
            <Layout>
              {children}
            </Layout>
          </SalaryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
